### ISSUE TITLE
Role is not idempotent

### ISSUE THREAD

**Issue by kostyrev** [groks/ansible-repo-google#4]
code

```
- hosts: localhost
  become: true
  roles:
    - groks.repo-google

  post_tasks:
    - name: install google software
      yum: name={{ item }} state=latest
      with_items:
        - google-chrome-stable
```

yields

```
TASK: [groks.repo-google | google yum repos] ********************************** 

changed: [localhost] => (item=chrome)
```
