### ISSUE TITLE
Does this "whacky google-script repo check" workaround work on Fedora?

### ISSUE THREAD

**Issue by sourcejedi** [groks/ansible-repo-google#5]
Hi

I wrote my own role specifically for google-chrome-stable on Fedora.  I stole your code

```
- name: disable whacky google-script repo check
  copy:
    dest: /etc/default/google-{{ item }}
    owner: root
    group: root
    mode: 0644
    content: |
      repo_add_once="false"
```

but this did not actually work in my testing.  I changed my role to follow the instructions at google.com/chrome,  "If you don’t want Google's repository, do `sudo touch /etc/default/google-chrome` before installing the package."  IOW, I modified the above code to say `content: ""`.  Then, it worked for me.

Without this change, my modifications to /etc/yum.repo.d/google-chrome.repo (to use a locally-maintained proxy cache as the baseurl) were overwritten when the google-chrome package was installed.

Just a suggestion, feel free to close :).
